### PR TITLE
Use new bulk_write method

### LINKED ISSUE #3: DeprecationWarning: initialize_ordered_bulk_op is deprecated
This may be a harmless py2-->py3 conversion issue but we should fix it at some point:

https://github.com/harvard-nrg/dpimport/blob/main/scripts/import.py#L109

```vim
INFO:__main__:document exists and is up to date /home/tb571/project_data/GENERAL/STUDY/SUBJECT/phone/processed/STUDY-SUBJECT-phone_surveyTimings_logbook_daily-day1to154.csv
INFO:__main__:cleaning metadata
/home/tb571/min3-dpdash/bin/import.py:109: DeprecationWarning: initialize_ordered_bulk_op is deprecated
  bulk_metadata = db.metadata.initialize_ordered_bulk_op()
```

### PR DESCRIPTION
**Pull request by blms**
Replacing the PR on https://github.com/harvard-nrg/dpimport — I had made it there since that's where the issue is, but this makes more sense.

Closes https://github.com/harvard-nrg/dpimport/issues/3 (when merged there, I imagine?)

### CODE REVIEW

**Comment by tashrifbillah** [comment]
> I had made it there since that's where the issue is

You are right, maybe then I was very optimistic that our work will be merged there 🦘

**Comment by tashrifbillah** [comment]
Can you write your status with big data export?

**Comment by blms** [comment]
> Can you write your status with big data export?

All seem to be successful! No errors during import with dpimport or during use of DPDash. I see 34 subjects, 1461 days on my dashboard.

**Comment by tashrifbillah** [comment]
Can you try a different type of import--one at a time?

**Review by tashrifbillah — APPROVED** [review]
LGTM

**Comment by blms** [comment]
> Can you try a different type of import--one at a time?

Yup, I did and that works too.

**Pull request merged**
